spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://production.host:5432/cluster_b # сюда нужно вписать url для вашей базы
    username: service_user_application
  jpa:
    show-sql: true

client:
  http:
    blacklist:
      uri: http://production-stend:8095/blacklist
    sanctions:
      uri: http://production-stend:8095/sanctions
      read-timeout-ms: 3000